# Elixir CircleCI 2.0 configuration file
# Check https://circleci.com/docs/2.0/language-elixir/ for more details
version: 2

workflows:
  version: 2
  test-build:
    jobs:
      - build
      - deploy

jobs:
  build:
    docker:
      # specify the version here
      - image: circleci/elixir:1.11
        environment:
          MIX_ENV: test
      - image: circleci/postgres:9.6.9-alpine

    working_directory: ~/repo
    steps:
      - checkout
      - run: mix local.hex --force # install Hex locally (without prompt)
      - run: mix local.rebar --force # fetch a copy of rebar (without prompt)
      - restore_cache:
          key: deps-cache-{{ checksum "mix.lock" }}
      - run: mix do deps.get, deps.compile
      - save_cache:
          key: deps-cache-{{ checksum "mix.lock" }}
          paths:
            - deps
            - ~/.mix
            - _build
      - run: mix compile --warnings-as-errors
      - run: # special utility that stalls main process until DB is ready
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run: mix do ecto.create, ecto.migrate
      - run: mix test
      - run: mix format --check-formatted
      - run: mix credo

  deploy:
    docker:
      - image: circleci/elixir:1.11
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install -y python-pip
      - run: sudo pip install gigalixir --ignore-installed six
      - run: gigalixir login -e "$GIGALIXIR_EMAIL" -y -p "$GIGALIXIR_PASSWORD"
      - run:
          name: banking-api-ex
          command: |
            echo 'export SUFFIX=$(echo $CIRCLE_BRANCH | tr "[:upper:]" "[:lower:]" | tr -cd "[a-z0-9-]")' >> $BASH_ENV
            echo 'export APP_NAME="$GIGALIXIR_APP_NAME-$SUFFIX"' >> $BASH_ENV
            source $BASH_ENV
      - run: gigalixir apps:destroy
      - run: gigalixir create --name $APP_NAME || gigalixir git:remote $APP_NAME
      - run: git push -f gigalixir HEAD:refs/heads/master